# Generated by Django 4.2.7 on 2023-11-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_building_alter_device_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=17)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='IpAddress',
            field=models.GenericIPAddressField(),
        ),
    ]
