# Generated by Django 4.2.7 on 2023-11-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_scanresult_alter_device_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='IpAddress',
            field=models.CharField(max_length=15),
        ),
    ]
