# Generated by Django 4.2.7 on 2023-11-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_scanresult_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ScanDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
    ]
