# Generated by Django 4.2.7 on 2023-11-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_scandate_delete_scanresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ScanDate',
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='IpAddress',
            field=models.GenericIPAddressField(),
        ),
    ]
