# Generated by Django 4.2.7 on 2023-11-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_device_scandate_device_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
